---
- name: Common Setup
  hosts: servers
  roles:
    - common
  tags:
    - common

- name: DNS Setup
  hosts: dns_servers
  roles:
    - dns_server
  tags:
    - dns
    - core

- name: Gitea Setup
  hosts: gitea_servers
  roles:
    - gitea_server
  tags:
    - gitea
    - core

- name: Setup Backups
  hosts: all
  roles:
    - backup
  tags:
    - common
    - backup

- name: Minecraft Setup
  hosts: minecraft_servers
  roles:
    - minecraft_server
  tags:
    - minecraft

- name: Ntfy Setup
  hosts: ntfy_servers
  roles:
    - ntfy_server
  tags:
    - ntfy
    - comms

- name: SilverBullet Setup
  hosts: silverbullet_servers
  roles:
    - silverbullet_server
  tags:
    - silverbullet
    - docs
