- name: Reload systemd User Daemon
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user
  become_user: "{{ ansible_user }}"

- name: Restart changed DNS Services
  ansible.builtin.systemd:
    name: "{{ item.item.name }}"
    state: restarted
    scope: user
  loop: "{{ dns_quadlet_results.results | selectattr('changed', 'equalto', true) | list }}"
